/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package practico9;

import java.awt.Color;
import javax.swing.JOptionPane;

/**
 *
 * @author Juan
 */
public class ej2 extends javax.swing.JFrame {

    /**
     * Creates new form ej2
     */
    public ej2() {
        
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Colores = new javax.swing.ButtonGroup();
        jButtonPrincipal = new javax.swing.JButton();
        jRadioButtonRojo = new javax.swing.JRadioButton();
        jRadioButtonAzul = new javax.swing.JRadioButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(500, 500));
        getContentPane().setLayout(null);

        jButtonPrincipal.setText("Boton");
        jButtonPrincipal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPrincipalActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonPrincipal);
        jButtonPrincipal.setBounds(150, 170, 72, 23);

        Colores.add(jRadioButtonRojo);
        jRadioButtonRojo.setText("Rojo");
        jRadioButtonRojo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonRojoActionPerformed(evt);
            }
        });
        getContentPane().add(jRadioButtonRojo);
        jRadioButtonRojo.setBounds(143, 74, 130, 21);

        Colores.add(jRadioButtonAzul);
        jRadioButtonAzul.setText("Azul");
        jRadioButtonAzul.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonAzulActionPerformed(evt);
            }
        });
        getContentPane().add(jRadioButtonAzul);
        jRadioButtonAzul.setBounds(143, 107, 220, 21);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jRadioButtonRojoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonRojoActionPerformed
        // TODO add your handling code here:
        this.jButtonPrincipal.setBackground(Color.red);
        
    }//GEN-LAST:event_jRadioButtonRojoActionPerformed

    private void jRadioButtonAzulActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonAzulActionPerformed
        // TODO add your handling code here:
        this.jButtonPrincipal.setBackground(Color.blue);
        
    }//GEN-LAST:event_jRadioButtonAzulActionPerformed

    private void jButtonPrincipalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPrincipalActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(null, "juanpe 19 años", "Datos creador", JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_jButtonPrincipalActionPerformed

    /**
     * @param args the command line arguments
     */
   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup Colores;
    private javax.swing.JButton jButtonPrincipal;
    private javax.swing.JRadioButton jRadioButtonAzul;
    private javax.swing.JRadioButton jRadioButtonRojo;
    // End of variables declaration//GEN-END:variables
}
