/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Interfaz;

/**
 *
 * @author Juan
 */
public class menuPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form menuPrincipal
     */
    public menuPrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        registro = new javax.swing.JMenu();
        registroEditorial = new javax.swing.JMenuItem();
        registroGenero = new javax.swing.JMenuItem();
        registroAutor = new javax.swing.JMenuItem();
        registroLibro = new javax.swing.JMenuItem();
        ventas = new javax.swing.JMenu();
        registrarVenta = new javax.swing.JMenuItem();
        anularVenta = new javax.swing.JMenuItem();
        consultas = new javax.swing.JMenu();
        consultaLibros = new javax.swing.JMenuItem();
        consultaVenta = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Gestión de librerias - Realizado por: Juan Pedro Longo (329112) - José Ignacio Arbilla (338084)");
        setMinimumSize(new java.awt.Dimension(500, 500));
        getContentPane().setLayout(null);

        registro.setText("Registros");

        registroEditorial.setText("Editorial");
        registro.add(registroEditorial);

        registroGenero.setText("Género");
        registro.add(registroGenero);

        registroAutor.setText("Autor");
        registroAutor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registroAutorActionPerformed(evt);
            }
        });
        registro.add(registroAutor);

        registroLibro.setText("Libro");
        registroLibro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registroLibroActionPerformed(evt);
            }
        });
        registro.add(registroLibro);

        jMenuBar1.add(registro);

        ventas.setText("Ventas");

        registrarVenta.setText("Registrar Venta");
        ventas.add(registrarVenta);

        anularVenta.setText("Anular Venta");
        anularVenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                anularVentaActionPerformed(evt);
            }
        });
        ventas.add(anularVenta);

        jMenuBar1.add(ventas);

        consultas.setText("Consultas");

        consultaLibros.setText("Consulta de libros");
        consultas.add(consultaLibros);

        consultaVenta.setText("Consulta de ventas");
        consultas.add(consultaVenta);

        jMenuBar1.add(consultas);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void registroAutorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registroAutorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_registroAutorActionPerformed

    private void registroLibroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registroLibroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_registroLibroActionPerformed

    private void anularVentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_anularVentaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_anularVentaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(menuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(menuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(menuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(menuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new menuPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem anularVenta;
    private javax.swing.JMenuItem consultaLibros;
    private javax.swing.JMenuItem consultaVenta;
    private javax.swing.JMenu consultas;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem registrarVenta;
    private javax.swing.JMenu registro;
    private javax.swing.JMenuItem registroAutor;
    private javax.swing.JMenuItem registroEditorial;
    private javax.swing.JMenuItem registroGenero;
    private javax.swing.JMenuItem registroLibro;
    private javax.swing.JMenu ventas;
    // End of variables declaration//GEN-END:variables
}
