package Interfaz;

import Dominio.Sistema;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.IOException;
import java.io.ObjectInputStream;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Juan
 */
public class ventInicio extends javax.swing.JFrame {

    Sistema sistema;

    /**
     * Creates new form ventInicio
     */
    public ventInicio(Sistema sis) {
        initComponents();
        sistema = sis;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jlbSisNuevo = new javax.swing.JLabel();
        jlbSisVie = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Inicio");

        jlbSisNuevo.setText("Utilizar el sistema con uno nuevo");

        jlbSisVie.setText("Utilizar el sistema de la ultima ejecucución");

        jButton1.setText("Ejecutar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Ejecutar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jlbSisVie)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 42, Short.MAX_VALUE)
                        .addComponent(jButton2))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jlbSisNuevo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton1)))
                .addGap(28, 28, 28))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlbSisNuevo)
                    .addComponent(jButton1))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jlbSisVie)
                    .addComponent(jButton2))
                .addContainerGap(191, Short.MAX_VALUE))
        );

        setSize(new java.awt.Dimension(414, 307));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        Sistema sistema = new Sistema();
        menuPrincipal vent = new menuPrincipal(sistema);
        vent.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        File file = new File("datos.ser");
        if (file.exists()) {
            FileInputStream ff;
            try {
                ff = new FileInputStream(file);
                ObjectInputStream gg = new ObjectInputStream(ff);
                Sistema sis = (Sistema) gg.readObject();
                menuPrincipal ventana = new menuPrincipal(sis);
                ventana.setVisible(true);
            } catch (FileNotFoundException ex) {
                JOptionPane.showMessageDialog(null,"Error no encotro el archivo", "Error", JOptionPane.ERROR_MESSAGE);

            }catch (IOException ex) {
                JOptionPane.showMessageDialog(null,"Error al leer archivo", "Error", JOptionPane.ERROR_MESSAGE);

            } catch (ClassNotFoundException ex) {
               JOptionPane.showMessageDialog(null,"Error al recuperar archivo", "Error", JOptionPane.ERROR_MESSAGE);

            }
            
        } else {
            JOptionPane.showMessageDialog(null,"No hay archivo guardado", "Error", JOptionPane.ERROR_MESSAGE);

        }
        this.dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
         * @param args the command line arguments
         */
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jlbSisNuevo;
    private javax.swing.JLabel jlbSisVie;
    // End of variables declaration//GEN-END:variables
}
