
package Interfaz;

/*
@author Juan Pedro Longo (329112)
@author Jose Ignacio Arbilla (338084)
 */
import Dominio.*;
import java.util.ArrayList;
import java.util.Observable;
import java.util.Observer;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;


public class ventRegGenero extends javax.swing.JFrame implements Observer{
    
    Sistema sistema;
    /**
     * Creates new form ventRegGenero
     */
    public ventRegGenero(Sistema sis) {
        initComponents();
        sistema=sis;
        //cargarLista();
        cargar();
        sis.addObserver(this);
    }
    
    public void update(Observable o, Object ob){
        cargar();
    }
     public void cargar(){
        if(sistema.getListaGeneros().size() >0){
            listaRegGen.setListData(sistema.getListaGeneros().toArray());
            pnlListaGen.setVisible(false);
        }else
            pnlListaGen.setVisible(true);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbRegGen = new javax.swing.JLabel();
        lbNomRegGen = new javax.swing.JLabel();
        pnlListaGen = new javax.swing.JPanel();
        lbDescRegGen = new javax.swing.JLabel();
        txtNomGen = new javax.swing.JTextField();
        txtDescGen = new javax.swing.JTextField();
        btnRegGen = new javax.swing.JButton();
        btnCancGen = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        listaRegGen = new javax.swing.JList();
        lbGenIngRegGen = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Registro de Genero");
        setMinimumSize(new java.awt.Dimension(500, 500));
        getContentPane().setLayout(null);

        lbRegGen.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lbRegGen.setForeground(new java.awt.Color(0, 171, 0));
        lbRegGen.setText("Registro de Género");
        getContentPane().add(lbRegGen);
        lbRegGen.setBounds(30, 20, 170, 25);

        lbNomRegGen.setText("Nombre del género:");
        getContentPane().add(lbNomRegGen);
        lbNomRegGen.setBounds(30, 70, 130, 16);
        getContentPane().add(pnlListaGen);
        pnlListaGen.setBounds(230, 10, 260, 230);

        lbDescRegGen.setText("Descripción del género:");
        getContentPane().add(lbDescRegGen);
        lbDescRegGen.setBounds(30, 120, 140, 16);

        txtNomGen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNomGenActionPerformed(evt);
            }
        });
        getContentPane().add(txtNomGen);
        txtNomGen.setBounds(30, 90, 170, 22);
        getContentPane().add(txtDescGen);
        txtDescGen.setBounds(30, 140, 170, 22);

        btnRegGen.setText("Registrar");
        btnRegGen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegGenActionPerformed(evt);
            }
        });
        getContentPane().add(btnRegGen);
        btnRegGen.setBounds(30, 190, 90, 23);

        btnCancGen.setText("Cancelar");
        btnCancGen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancGenActionPerformed(evt);
            }
        });
        getContentPane().add(btnCancGen);
        btnCancGen.setBounds(130, 190, 90, 23);

        jScrollPane1.setViewportView(listaRegGen);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(260, 50, 220, 180);

        lbGenIngRegGen.setText("Lista de géneros ingresados");
        getContentPane().add(lbGenIngRegGen);
        lbGenIngRegGen.setBounds(270, 20, 190, 20);

        setSize(new java.awt.Dimension(516, 256));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnRegGenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegGenActionPerformed
        // TODO add your handling code here:
        if(sistema.regGenero(txtNomGen.getText(), txtDescGen.getText())){
            JOptionPane.showMessageDialog(null,"Se guardo el Género", "info", JOptionPane.INFORMATION_MESSAGE);
            cargar();
            actualizar();
        }else{
            //si ya existe muestra mensaje de error
            JOptionPane.showMessageDialog(null,"Ya exise genero con ese nombre", "Error", JOptionPane.ERROR_MESSAGE);
            actualizar();
       }
    }//GEN-LAST:event_btnRegGenActionPerformed

    private void btnCancGenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancGenActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_btnCancGenActionPerformed

    private void txtNomGenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNomGenActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNomGenActionPerformed
     public void actualizar(){
        txtNomGen.setText("");
        txtDescGen.setText("");
    }
   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancGen;
    private javax.swing.JButton btnRegGen;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbDescRegGen;
    private javax.swing.JLabel lbGenIngRegGen;
    private javax.swing.JLabel lbNomRegGen;
    private javax.swing.JLabel lbRegGen;
    private javax.swing.JList listaRegGen;
    private javax.swing.JPanel pnlListaGen;
    private javax.swing.JTextField txtDescGen;
    private javax.swing.JTextField txtNomGen;
    // End of variables declaration//GEN-END:variables
}
