/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Interfaz;

/**
 *
 * @author Juan
 */
public class ventRegGenero extends javax.swing.JFrame {

    /**
     * Creates new form ventRegGenero
     */
    public ventRegGenero() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtNomGen = new javax.swing.JTextField();
        txtDescGen = new javax.swing.JTextField();
        btnRegGen = new javax.swing.JButton();
        btnCancGen = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        listaRegGen = new javax.swing.JList<>();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Registro de Genero");
        getContentPane().setLayout(null);

        jLabel1.setText("Registro de Género");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(30, 20, 130, 16);

        jLabel2.setText("Nombre del género:");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(30, 70, 130, 16);

        jLabel3.setText("Descripción del género:");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(30, 120, 140, 16);
        getContentPane().add(txtNomGen);
        txtNomGen.setBounds(30, 90, 170, 22);
        getContentPane().add(txtDescGen);
        txtDescGen.setBounds(30, 140, 170, 22);

        btnRegGen.setText("Registrar");
        btnRegGen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegGenActionPerformed(evt);
            }
        });
        getContentPane().add(btnRegGen);
        btnRegGen.setBounds(30, 190, 80, 23);

        btnCancGen.setText("Cancelar");
        btnCancGen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancGenActionPerformed(evt);
            }
        });
        getContentPane().add(btnCancGen);
        btnCancGen.setBounds(120, 190, 76, 23);

        listaRegGen.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(listaRegGen);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(260, 50, 220, 180);

        jLabel4.setText("Lista de géneros ingresados");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(270, 20, 190, 20);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnRegGenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegGenActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_btnRegGenActionPerformed

    private void btnCancGenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancGenActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_btnCancGenActionPerformed

    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancGen;
    private javax.swing.JButton btnRegGen;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JList<String> listaRegGen;
    private javax.swing.JTextField txtDescGen;
    private javax.swing.JTextField txtNomGen;
    // End of variables declaration//GEN-END:variables
}
