
package Interfaz;

import Dominio.Sistema;
import javax.swing.JOptionPane;


/*
@author Juan Pedro Longo (329112)
@author Jose Ignacio Arbilla (338084)
 */
public class ventConsLibros extends javax.swing.JFrame {

    Sistema sistema;
    /**
     * Creates new form ventConsLibros
     */
    public ventConsLibros(Sistema sis) {
        initComponents();
        sistema=sis;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtGenConsLibro = new javax.swing.JTextField();
        txtTitConsLibro = new javax.swing.JTextField();
        txtAutConsLibro = new javax.swing.JTextField();
        lbTitConsLib = new javax.swing.JLabel();
        lbAutConsLib = new javax.swing.JLabel();
        btnConsLibros = new javax.swing.JButton();
        lbGenConsLib = new javax.swing.JLabel();
        lbConsLib = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Consulta de Libros");

        lbTitConsLib.setText("Título:");

        lbAutConsLib.setText("Autor:");

        btnConsLibros.setText("Consultar");
        btnConsLibros.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConsLibrosActionPerformed(evt);
            }
        });

        lbGenConsLib.setText("Género:");

        lbConsLib.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lbConsLib.setForeground(new java.awt.Color(0, 0, 255));
        lbConsLib.setText("Consulta de libros");

        jPanel1.setLayout(new java.awt.GridLayout(1, 0));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbTitConsLib)
                            .addComponent(lbAutConsLib)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(txtGenConsLibro)
                                .addComponent(txtTitConsLibro)
                                .addComponent(txtAutConsLibro, javax.swing.GroupLayout.DEFAULT_SIZE, 226, Short.MAX_VALUE))
                            .addComponent(lbGenConsLib)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(92, 92, 92)
                        .addComponent(btnConsLibros)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(16, 16, 16))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 122, Short.MAX_VALUE)
                .addComponent(lbConsLib)
                .addGap(269, 269, 269))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lbConsLib)
                        .addGap(24, 24, 24)
                        .addComponent(lbGenConsLib)
                        .addGap(18, 18, 18)
                        .addComponent(txtGenConsLibro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(26, 26, 26)
                        .addComponent(lbTitConsLib)
                        .addGap(18, 18, 18)
                        .addComponent(txtTitConsLibro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(32, 32, 32)
                        .addComponent(lbAutConsLib)
                        .addGap(18, 18, 18)
                        .addComponent(txtAutConsLibro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(23, 23, 23)
                        .addComponent(btnConsLibros)))
                .addContainerGap(21, Short.MAX_VALUE))
        );

        setSize(new java.awt.Dimension(559, 355));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnConsLibrosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConsLibrosActionPerformed
        // TODO add your handling code here:
        if(txtAutConsLibro.getText().trim().equals("") && txtGenConsLibro.getText().trim().equals("") 
                && txtTitConsLibro.getText().trim().equals("")){
            JOptionPane.showMessageDialog(null, "No se puede consultar un libro sin ningun dato", "Error", JOptionPane.ERROR_MESSAGE);
        }else{
            if(!sistema.chequiarLibro(txtTitConsLibro.getText(), txtAutConsLibro.getText(),
                    txtGenConsLibro.getText())){
                JOptionPane.showMessageDialog(null, "No existe ningun libro con esos datos", "Error", JOptionPane.ERROR_MESSAGE);
            }else{
                
            }
        }
    }//GEN-LAST:event_btnConsLibrosActionPerformed

    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnConsLibros;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lbAutConsLib;
    private javax.swing.JLabel lbConsLib;
    private javax.swing.JLabel lbGenConsLib;
    private javax.swing.JLabel lbTitConsLib;
    private javax.swing.JTextField txtAutConsLibro;
    private javax.swing.JTextField txtGenConsLibro;
    private javax.swing.JTextField txtTitConsLibro;
    // End of variables declaration//GEN-END:variables
}
