/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Interfaz;

/**
 *
 * @author Juan
 */
public class ventAnularVenta extends javax.swing.JFrame {

    /**
     * Creates new form ventAnularVenta
     */
    public ventAnularVenta() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbFacAnuVenta = new javax.swing.JLabel();
        txtNumFact = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList<>();
        lbDatAnuVenta = new javax.swing.JLabel();
        btnAnular = new javax.swing.JButton();
        btnCancAnular = new javax.swing.JButton();
        lbAnuVenta = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Anular Venta");
        getContentPane().setLayout(null);

        lbFacAnuVenta.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lbFacAnuVenta.setText("Ingrese el número de factura: ");
        getContentPane().add(lbFacAnuVenta);
        lbFacAnuVenta.setBounds(30, 50, 210, 20);
        getContentPane().add(txtNumFact);
        txtNumFact.setBounds(220, 50, 100, 22);

        jScrollPane1.setViewportView(jList1);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(30, 110, 270, 140);

        lbDatAnuVenta.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lbDatAnuVenta.setText("Datos de la Venta:");
        getContentPane().add(lbDatAnuVenta);
        lbDatAnuVenta.setBounds(30, 80, 160, 20);

        btnAnular.setText("Anular");
        getContentPane().add(btnAnular);
        btnAnular.setBounds(230, 270, 72, 23);

        btnCancAnular.setText("Cancelar");
        btnCancAnular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancAnularActionPerformed(evt);
            }
        });
        getContentPane().add(btnCancAnular);
        btnCancAnular.setBounds(320, 270, 76, 23);

        lbAnuVenta.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lbAnuVenta.setForeground(new java.awt.Color(255, 0, 0));
        lbAnuVenta.setText("Anular Venta");
        getContentPane().add(lbAnuVenta);
        lbAnuVenta.setBounds(110, 10, 160, 20);

        setSize(new java.awt.Dimension(414, 307));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnCancAnularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancAnularActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_btnCancAnularActionPerformed

   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAnular;
    private javax.swing.JButton btnCancAnular;
    private javax.swing.JList<String> jList1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbAnuVenta;
    private javax.swing.JLabel lbDatAnuVenta;
    private javax.swing.JLabel lbFacAnuVenta;
    private javax.swing.JTextField txtNumFact;
    // End of variables declaration//GEN-END:variables
}
