/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Interfaz;

import Dominio.*;
import java.util.ArrayList;
import java.util.Observable;
import java.util.Observer;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;

/**
 *
 * @author Juan
 */
public class ventRegLibro extends javax.swing.JFrame implements Observer {
    
    Sistema sistema;
    /**
     * Creates new form ventRegLibro
     */
    public ventRegLibro(Sistema sis) {
        initComponents();
        sistema=sis;
        cargarListaEditoriales();
        cargarListaGenero();
     
        sis.addObserver(this);
    }

     public void update(Observable o, Object ob){
        cargarListaEditoriales();
        cargarListaGenero();
        
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane3 = new javax.swing.JScrollPane();
        lbRegLibro = new javax.swing.JLabel();
        lbTitRegLib = new javax.swing.JLabel();
        txtTituloLibro = new javax.swing.JTextField();
        lbEdiRegLib = new javax.swing.JLabel();
        lbGenRegLib = new javax.swing.JLabel();
        lbAutRegLib = new javax.swing.JLabel();
        lbPrecCosRegLib = new javax.swing.JLabel();
        txtPrecioCosto = new javax.swing.JTextField();
        lbisbnRegLib = new javax.swing.JLabel();
        txtISBN = new javax.swing.JTextField();
        lbPrecVentaRegLib = new javax.swing.JLabel();
        txtPrecioVenta = new javax.swing.JTextField();
        btnRegLibro = new javax.swing.JButton();
        btnCancLibro = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        listGenero = new javax.swing.JList();
        jScrollPane2 = new javax.swing.JScrollPane();
        listEdi = new javax.swing.JList();
        jScrollPane4 = new javax.swing.JScrollPane();
        listAut = new javax.swing.JList();
        btnFoto = new javax.swing.JButton();
        lbFotoRegLib = new javax.swing.JLabel();
        txtStock = new javax.swing.JTextField();
        lbStockRegLib = new javax.swing.JLabel();
        pnllistGen = new javax.swing.JPanel();
        pnlListEdi = new javax.swing.JPanel();
        pnlListAut = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Registro de Libro");
        setMinimumSize(new java.awt.Dimension(500, 500));
        getContentPane().setLayout(null);

        lbRegLibro.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lbRegLibro.setForeground(new java.awt.Color(0, 171, 0));
        lbRegLibro.setText("Registrar Libro");
        getContentPane().add(lbRegLibro);
        lbRegLibro.setBounds(28, 17, 170, 25);

        lbTitRegLib.setText("Titulo");
        getContentPane().add(lbTitRegLib);
        lbTitRegLib.setBounds(30, 50, 30, 16);
        getContentPane().add(txtTituloLibro);
        txtTituloLibro.setBounds(30, 70, 180, 22);

        lbEdiRegLib.setText("Editorial:");
        getContentPane().add(lbEdiRegLib);
        lbEdiRegLib.setBounds(30, 160, 70, 16);

        lbGenRegLib.setText("Género:");
        getContentPane().add(lbGenRegLib);
        lbGenRegLib.setBounds(30, 100, 60, 16);

        lbAutRegLib.setText("Autor:");
        getContentPane().add(lbAutRegLib);
        lbAutRegLib.setBounds(30, 210, 33, 16);

        lbPrecCosRegLib.setText("Precio costo");
        getContentPane().add(lbPrecCosRegLib);
        lbPrecCosRegLib.setBounds(230, 130, 70, 16);
        getContentPane().add(txtPrecioCosto);
        txtPrecioCosto.setBounds(230, 150, 64, 22);

        lbisbnRegLib.setText("ISBN");
        getContentPane().add(lbisbnRegLib);
        lbisbnRegLib.setBounds(320, 50, 25, 16);

        txtISBN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtISBNActionPerformed(evt);
            }
        });
        getContentPane().add(txtISBN);
        txtISBN.setBounds(320, 70, 71, 22);

        lbPrecVentaRegLib.setText("Precio venta");
        getContentPane().add(lbPrecVentaRegLib);
        lbPrecVentaRegLib.setBounds(320, 130, 65, 16);
        getContentPane().add(txtPrecioVenta);
        txtPrecioVenta.setBounds(320, 150, 64, 22);

        btnRegLibro.setText("Registrar");
        btnRegLibro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegLibroActionPerformed(evt);
            }
        });
        getContentPane().add(btnRegLibro);
        btnRegLibro.setBounds(210, 260, 80, 23);

        btnCancLibro.setText("Cancelar");
        btnCancLibro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancLibroActionPerformed(evt);
            }
        });
        getContentPane().add(btnCancLibro);
        btnCancLibro.setBounds(310, 260, 76, 23);

        listGenero.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        listGenero.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                listGeneroValueChanged(evt);
            }
        });
        jScrollPane1.setViewportView(listGenero);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(30, 120, 140, 30);

        jScrollPane2.setToolTipText("");

        listEdi.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPane2.setViewportView(listEdi);

        getContentPane().add(jScrollPane2);
        jScrollPane2.setBounds(27, 176, 150, 30);

        listAut.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPane4.setViewportView(listAut);

        getContentPane().add(jScrollPane4);
        jScrollPane4.setBounds(30, 230, 150, 40);

        btnFoto.setText("Subir foto");
        btnFoto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFotoActionPerformed(evt);
            }
        });
        getContentPane().add(btnFoto);
        btnFoto.setBounds(260, 210, 90, 23);

        lbFotoRegLib.setText("Foto");
        getContentPane().add(lbFotoRegLib);
        lbFotoRegLib.setBounds(290, 190, 40, 16);

        txtStock.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtStockActionPerformed(evt);
            }
        });
        getContentPane().add(txtStock);
        txtStock.setBounds(230, 70, 64, 22);

        lbStockRegLib.setText("Stock");
        getContentPane().add(lbStockRegLib);
        lbStockRegLib.setBounds(230, 50, 29, 16);
        getContentPane().add(pnllistGen);
        pnllistGen.setBounds(10, 100, 180, 60);
        getContentPane().add(pnlListEdi);
        pnlListEdi.setBounds(20, 160, 170, 50);
        getContentPane().add(pnlListAut);
        pnlListAut.setBounds(10, 210, 190, 70);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCancLibroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancLibroActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_btnCancLibroActionPerformed

    private void btnFotoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFotoActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_btnFotoActionPerformed

    private void listGeneroValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_listGeneroValueChanged
        // TODO add your handling code here:
        //se toma con el index el numero que tiene ese genero seleccionado y se toma de la lista de generos
        Genero gen= sistema.getListaGeneros().get(listGenero.getSelectedIndex());
        cargarListaAutores(gen);
    }//GEN-LAST:event_listGeneroValueChanged

    private void txtISBNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtISBNActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_txtISBNActionPerformed

    private void btnRegLibroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegLibroActionPerformed
        // TODO add your handling code here:
        //a la hora de registrar el libro hay que fijarse si ya existia el isbn
        try{
            if(!sistema.chequearISBN(txtISBN.getText())){
                JOptionPane.showMessageDialog(null,"ISBN duplicado", "Error", JOptionPane.ERROR_MESSAGE);
                txtISBN.setText("");
                
            }else if(Integer.parseInt(txtStock.getText())<=0){
                //chequeo del stock, tiene que ser mayor a 0
                JOptionPane.showMessageDialog(null,"El stock debe de ser mayor que 0", "Error", JOptionPane.ERROR_MESSAGE);
                txtStock.setText("");
            }
            else{
                //si los datos anterirores estan bien, hay que crear el libro y agregarlo a la lista
                Genero gen= (Genero) listGenero.getSelectedValue();
                Editorial edi=  (Editorial) listEdi.getSelectedValue();
                Autor aut=  (Autor) listAut.getSelectedValue();
                
                //hay que parsear los datos que vienen en string
                int stcok = Integer.parseInt(txtStock.getText());
                int precioCosto = Integer.parseInt(txtPrecioCosto.getText());
                int precioVenta =Integer.parseInt(txtPrecioVenta.getText());
                
                if(gen != null && edi !=null && aut!=null){
                    Libro lib=new Libro(txtTituloLibro.getText(), edi, txtISBN.getText(), aut, gen, stcok, precioCosto, precioVenta);
                    sistema.getListaLibros().add(lib);
                    JOptionPane.showMessageDialog(null,"guardo", "Info", JOptionPane.INFORMATION_MESSAGE);
                }else{
                    JOptionPane.showMessageDialog(null,"Debe seleccion genero, editorial y autor", "Error", JOptionPane.ERROR_MESSAGE);
                }
                
                
            }
        }catch(Exception e){
            JOptionPane.showMessageDialog(null,"El stock no puede estar vacio y debe ser un número", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnRegLibroActionPerformed

    private void txtStockActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtStockActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtStockActionPerformed
    
    //se carga la lista de generos
    public void cargarListaGenero(){
        if(sistema.getListaGeneros().size() >0){
            listGenero.setListData(sistema.getListaGeneros().toArray());
            //pnllistGen.setVisible(false);
        //}else{
          //  pnllistGen.setVisible(true);
        }
    }
    
    //se carga la lista de editoriales
    public void cargarListaEditoriales(){
        listEdi.setListData(sistema.getListaEditoriales().toArray());
    }
    
    //se carga la lista de autores dependiendo del genero que escriban
    public void cargarListaAutores(Genero gen){
        listAut.setListData(sistema.getAutoresPorGénero(gen).toArray());
        
    }
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancLibro;
    private javax.swing.JButton btnFoto;
    private javax.swing.JButton btnRegLibro;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JLabel lbAutRegLib;
    private javax.swing.JLabel lbEdiRegLib;
    private javax.swing.JLabel lbFotoRegLib;
    private javax.swing.JLabel lbGenRegLib;
    private javax.swing.JLabel lbPrecCosRegLib;
    private javax.swing.JLabel lbPrecVentaRegLib;
    private javax.swing.JLabel lbRegLibro;
    private javax.swing.JLabel lbStockRegLib;
    private javax.swing.JLabel lbTitRegLib;
    private javax.swing.JLabel lbisbnRegLib;
    private javax.swing.JList listAut;
    private javax.swing.JList listEdi;
    private javax.swing.JList listGenero;
    private javax.swing.JPanel pnlListAut;
    private javax.swing.JPanel pnlListEdi;
    private javax.swing.JPanel pnllistGen;
    private javax.swing.JTextField txtISBN;
    private javax.swing.JTextField txtPrecioCosto;
    private javax.swing.JTextField txtPrecioVenta;
    private javax.swing.JTextField txtStock;
    private javax.swing.JTextField txtTituloLibro;
    // End of variables declaration//GEN-END:variables
}
