/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Interfaz;

/**
 *
 * @author Usuario
 */
public class ventConsVentas extends javax.swing.JFrame {

    /**
     * Creates new form ventConsVentas
     */
    public ventConsVentas() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        isbnConsVenta = new javax.swing.JTextField();
        btnConsVenta = new javax.swing.JButton();
        btnExpVenta = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaConsVentas = new javax.swing.JTable();
        tituloConsVenta = new javax.swing.JLabel();
        btnLibrosIngConsVent = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        listaLibrosIngConsVent = new javax.swing.JList<>();
        jLabel2 = new javax.swing.JLabel();
        nroTotRecConsVen = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        nroTotGanConsVen = new javax.swing.JLabel();
        nroEjVendConsVen2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Consulta de Ventas");
        getContentPane().setLayout(null);

        jLabel1.setText("ISBN");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(20, 20, 30, 20);
        getContentPane().add(isbnConsVenta);
        isbnConsVenta.setBounds(50, 20, 200, 22);

        btnConsVenta.setText("Consultar");
        btnConsVenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConsVentaActionPerformed(evt);
            }
        });
        getContentPane().add(btnConsVenta);
        btnConsVenta.setBounds(320, 20, 90, 23);

        btnExpVenta.setText("Exportar");
        getContentPane().add(btnExpVenta);
        btnExpVenta.setBounds(450, 20, 74, 23);

        tablaConsVentas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Fecha", "Cliente", "Factura", "Cantidad", "Precio", "Ingreso"
            }
        ));
        jScrollPane1.setViewportView(tablaConsVentas);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(30, 100, 510, 220);

        tituloConsVenta.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        tituloConsVenta.setForeground(new java.awt.Color(0, 0, 255));
        tituloConsVenta.setText("Título del Libro");
        getContentPane().add(tituloConsVenta);
        tituloConsVenta.setBounds(40, 70, 220, 20);

        btnLibrosIngConsVent.setText("...");
        btnLibrosIngConsVent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLibrosIngConsVentActionPerformed(evt);
            }
        });
        getContentPane().add(btnLibrosIngConsVent);
        btnLibrosIngConsVent.setBounds(260, 20, 30, 23);

        listaLibrosIngConsVent.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane2.setViewportView(listaLibrosIngConsVent);

        getContentPane().add(jScrollPane2);
        jScrollPane2.setBounds(350, 60, 190, 250);

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setText("Total recaudado");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(250, 330, 150, 20);

        nroTotRecConsVen.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        nroTotRecConsVen.setForeground(new java.awt.Color(0, 0, 255));
        nroTotRecConsVen.setText("nro");
        getContentPane().add(nroTotRecConsVen);
        nroTotRecConsVen.setBounds(290, 350, 70, 20);

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setText("Total ganancias");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(430, 330, 130, 20);

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel4.setText("Ejemplares vendidos");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(40, 330, 150, 20);

        nroTotGanConsVen.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        nroTotGanConsVen.setForeground(new java.awt.Color(0, 0, 255));
        nroTotGanConsVen.setText("nro");
        getContentPane().add(nroTotGanConsVen);
        nroTotGanConsVen.setBounds(470, 350, 70, 20);

        nroEjVendConsVen2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        nroEjVendConsVen2.setForeground(new java.awt.Color(0, 0, 255));
        nroEjVendConsVen2.setText("nro");
        getContentPane().add(nroEjVendConsVen2);
        nroEjVendConsVen2.setBounds(90, 350, 80, 20);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnConsVentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConsVentaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnConsVentaActionPerformed

    private void btnLibrosIngConsVentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLibrosIngConsVentActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnLibrosIngConsVentActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ventConsVentas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ventConsVentas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ventConsVentas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ventConsVentas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ventConsVentas().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnConsVenta;
    private javax.swing.JButton btnExpVenta;
    private javax.swing.JButton btnLibrosIngConsVent;
    private javax.swing.JTextField isbnConsVenta;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JList<String> listaLibrosIngConsVent;
    private javax.swing.JLabel nroEjVendConsVen2;
    private javax.swing.JLabel nroTotGanConsVen;
    private javax.swing.JLabel nroTotRecConsVen;
    private javax.swing.JTable tablaConsVentas;
    private javax.swing.JLabel tituloConsVenta;
    // End of variables declaration//GEN-END:variables
}
