/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Interfaz;

/**
 *
 * @author Juan
 */
public class ventRegVentas extends javax.swing.JFrame {

    /**
     * Creates new form ventRegVentas
     */
    public ventRegVentas() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtFechaVenta = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtNombreCliente = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList<>();
        btneliminarlbr = new javax.swing.JButton();
        btnAgregarlbr1 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jList2 = new javax.swing.JList<>();
        jLabel6 = new javax.swing.JLabel();
        btnCancVenta = new javax.swing.JButton();
        btnRegVenta = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Venta de Libros");
        getContentPane().setLayout(null);

        jLabel1.setText("Factura : número");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(20, 20, 110, 16);

        jLabel2.setText("Fecha");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(20, 50, 30, 16);

        txtFechaVenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFechaVentaActionPerformed(evt);
            }
        });
        getContentPane().add(txtFechaVenta);
        txtFechaVenta.setBounds(60, 50, 200, 22);

        jLabel3.setText("Cliente");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(280, 50, 37, 16);

        txtNombreCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNombreClienteActionPerformed(evt);
            }
        });
        getContentPane().add(txtNombreCliente);
        txtNombreCliente.setBounds(330, 50, 230, 22);

        jLabel4.setText("Libros");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(20, 100, 32, 16);

        jList1.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(jList1);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(20, 120, 220, 120);

        btneliminarlbr.setText("<-");
        btneliminarlbr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btneliminarlbrActionPerformed(evt);
            }
        });
        getContentPane().add(btneliminarlbr);
        btneliminarlbr.setBounds(260, 190, 50, 40);

        btnAgregarlbr1.setText("->");
        btnAgregarlbr1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarlbr1ActionPerformed(evt);
            }
        });
        getContentPane().add(btnAgregarlbr1);
        btnAgregarlbr1.setBounds(260, 140, 50, 40);

        jLabel5.setText("Venta");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(340, 100, 30, 16);

        jList2.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane2.setViewportView(jList2);

        getContentPane().add(jScrollPane2);
        jScrollPane2.setBounds(330, 120, 230, 120);

        jLabel6.setText("Total: $ número total de venta");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(330, 260, 220, 16);

        btnCancVenta.setText("Cancelar");
        btnCancVenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancVentaActionPerformed(evt);
            }
        });
        getContentPane().add(btnCancVenta);
        btnCancVenta.setBounds(390, 300, 74, 23);

        btnRegVenta.setText("Registrar");
        getContentPane().add(btnRegVenta);
        btnRegVenta.setBounds(130, 300, 80, 23);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtFechaVentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFechaVentaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFechaVentaActionPerformed

    private void txtNombreClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNombreClienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNombreClienteActionPerformed

    private void btneliminarlbrActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btneliminarlbrActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btneliminarlbrActionPerformed

    private void btnAgregarlbr1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarlbr1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnAgregarlbr1ActionPerformed

    private void btnCancVentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancVentaActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_btnCancVentaActionPerformed

   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgregarlbr1;
    private javax.swing.JButton btnCancVenta;
    private javax.swing.JButton btnRegVenta;
    private javax.swing.JButton btneliminarlbr;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JList<String> jList1;
    private javax.swing.JList<String> jList2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField txtFechaVenta;
    private javax.swing.JTextField txtNombreCliente;
    // End of variables declaration//GEN-END:variables
}
