/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Interfaz;

/**
 *
 * @author Juan
 */
public class ventRegLibro extends javax.swing.JFrame {

    /**
     * Creates new form ventRegLibro
     */
    public ventRegLibro() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtTituloLibro = new javax.swing.JTextField();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jRadioButton3 = new javax.swing.JRadioButton();
        jLabel6 = new javax.swing.JLabel();
        txtPrecioCosto = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtISBN = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txtPrecioVenta = new javax.swing.JTextField();
        btnRegLibro = new javax.swing.JButton();
        btnCancLibro = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Registro de Libro");
        getContentPane().setLayout(null);

        jLabel1.setText("Registrar Libro");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(28, 17, 170, 16);

        jLabel2.setText("Titulo");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(30, 50, 29, 16);
        getContentPane().add(txtTituloLibro);
        txtTituloLibro.setBounds(30, 70, 64, 22);

        jRadioButton1.setText("jRadioButton1");
        getContentPane().add(jRadioButton1);
        jRadioButton1.setBounds(30, 120, 98, 21);

        jRadioButton2.setText("jRadioButton2");
        getContentPane().add(jRadioButton2);
        jRadioButton2.setBounds(30, 180, 98, 21);

        jLabel3.setText("Editorial:");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(30, 160, 70, 16);

        jLabel4.setText("Género:");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(30, 100, 60, 16);

        jLabel5.setText("Autor:");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(30, 210, 33, 16);

        jRadioButton3.setText("jRadioButton3");
        getContentPane().add(jRadioButton3);
        jRadioButton3.setBounds(30, 230, 98, 21);

        jLabel6.setText("Precio costo");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(210, 100, 70, 16);
        getContentPane().add(txtPrecioCosto);
        txtPrecioCosto.setBounds(210, 120, 64, 22);

        jLabel7.setText("ISBN");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(210, 170, 25, 16);
        getContentPane().add(txtISBN);
        txtISBN.setBounds(210, 190, 71, 22);

        jLabel8.setText("Precio venta");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(330, 100, 64, 16);
        getContentPane().add(txtPrecioVenta);
        txtPrecioVenta.setBounds(330, 120, 64, 22);

        btnRegLibro.setText("Registrar");
        getContentPane().add(btnRegLibro);
        btnRegLibro.setBounds(210, 260, 80, 23);

        btnCancLibro.setText("Cancelar");
        btnCancLibro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancLibroActionPerformed(evt);
            }
        });
        getContentPane().add(btnCancLibro);
        btnCancLibro.setBounds(310, 260, 74, 23);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCancLibroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancLibroActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_btnCancLibroActionPerformed

   
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancLibro;
    private javax.swing.JButton btnRegLibro;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JRadioButton jRadioButton3;
    private javax.swing.JTextField txtISBN;
    private javax.swing.JTextField txtPrecioCosto;
    private javax.swing.JTextField txtPrecioVenta;
    private javax.swing.JTextField txtTituloLibro;
    // End of variables declaration//GEN-END:variables
}
